// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iufuerdjyhnipraaabvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZnVlcmRqeWhuaXByYWFhYnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzc4NjIsImV4cCI6MjA2OTYxMzg2Mn0.uz6PuEC-66gCrO2qt-bhb-34l9TJQawl9wkBh5XtQ6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});